name: WorldEdit_Power_up
version: 1.3
main: WorldEdit_Power_up.Main
api-version: 1.16

commands:
  /check:
  /save_loc:
  config_test:
  config_reload:
  config_save:
  boyboy0710:
  boy0710boy:
  Calculation:
  test:
